language: node_js
node_js: 8

before_script:
  - npm install -g gulp-cli

script: make build-live

before_deploy:
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path

deploy:
  provider: script
  skip_cleanup: true
  script:
    - aws s3 sync dist/css s3://s3-eu-west-1.amazonaws.com/matt.rayner.io/css --delete # sync CSS
    - aws s3 sync dist/js s3://s3-eu-west-1.amazonaws.com/matt.rayner.io/js --delete # sync JS
    - aws s3 sync dist/assets s3://s3-eu-west-1.amazonaws.com/matt.rayner.io/assets --delete # sync Assets
    - aws s3 sync dist/*.html s3://s3-eu-west-1.amazonaws.com/matt.rayner.io/ # sync HTML
    - aws s3 mv s3://s3-eu-west-1.amazonaws.com/matt.rayner.io/about.html s3://s3-eu-west-1.amazonaws.com/matt.rayner.io/about # update About